[package]
name = "postar"
version = "0.1.0"
edition = "2024"
description = "A local email filtering service"
license = "MIT"
repository = "https://github.com/filiptrplan/postar"
readme = "README.md"
keywords = ["email", "filtering", "imap"]
categories = ["email", "command-line-utilities"]

[dependencies]
anyhow = "1.0.100"
ariadne = "0.6.0"
chrono = "0.4.42"
chumsky = "0.11.2"
clap = { version = "4.5.53", features = ["derive", "string", "unstable-doc"] }
imap = "2.4.1"
imap-proto = "^0.10"
log = "0.4.28"
logos = "0.15.1"
mail-parser = "0.11.1"
native-tls = "0.2.14"
ouroboros = "0.18.5"
regex = "1.12.2"
toml = "0.9.10"
rusqlite = "0.37.0"
rusqlite_migration = "2.3.0"
serde = { version = "1.0.228", features = ["derive"] }
dirs = "6.0.0"
env_logger = "0.11.8"
clap_complete = "4.5.64"

[dev-dependencies]
mail-send = "0.5.2"
once_cell = "1.21.3"
test-log = "0.2.18"
testcontainers = "0.25.2"
tokio = "1.48.0"
